services:
  - type: web
    name: throne-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health 
  - type: static
    name: throne-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build && npm run export
    staticPublishPath: out
    autoDeploy: true
